# Generated by Django 4.2.3 on 2023-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondChanceEmporiumApp', '0002_alter_shopuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
