# Generated by Django 4.2.3 on 2023-08-03 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecondChanceEmporiumApp', '0003_alter_shopuser_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products', models.ManyToManyField(blank=True, to='SecondChanceEmporiumApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecondChanceEmporiumApp.shopuser')),
            ],
        ),
    ]
